### ISSUE TITLE
The HTML format is all lost

### ISSUE THREAD

**Issue by Andy-AO** [GeeLaw/PowerShellThingies#3]
Execute  `Get-ConsoleLog | Set-Content ou222.html`, output to "ou222.html",but,the HTML format is all lost.

![image](https://user-images.githubusercontent.com/38101170/86884740-9753f000-c126-11ea-8d6d-f7c473092cc6.png)

**Comment by GeeLaw** [comment]
`Get-ConsoleLog` by default outputs a “clean” HTML fragment. You can control the stylesheet embedding mechanism using `-Css` parameter. In `Get-Help Get-ConsoleLog -ShowWindow`:

```text
-Css <String>
    Determines whether and how CSS is incorporated, can be one of
        Embed | Link | None
    and `None` is the default.  It is ignored if `Format` is not `Html`.

    Required?                    false
    Position?                    named
    Default value                None
    Accept pipeline input?       false
    Accept wildcard characters?  false
```
