### ISSUE TITLE
Questions about ConsoleLog module

### ISSUE THREAD

**Issue by Andy-AO** [GeeLaw/PowerShellThingies#4]
ConsoleLog can only save the currently visible content. The previous content cannot be exported. Can the current solution export all the contents?

**Comment by GeeLaw** [comment]
It saves all the *scrollable* content and it cannot do more without being a terminal emulator. A terminal emulator might set the console buffer to be small and copies data into another buffer managed by them. The console API can only access the console buffer, and not the buffer managed by them.

If you are using `conhost.exe`, open the context menu of the console window (title bar) and click "Properties", then in "Layout" tab, change the screen buffer size.

If you are using Windows Terminal or the integrated terminal of VSCode, there is no way of saving more than the "screen size". They are terminal emulators and set the console buffer to be just large enough to hold one screen, and the "scrollable content" is not part of the Windows Console and is just an illusion provided by the emulators.
